"""update created_at and updated_at, note.text - str

Revision ID: 87a2e836d4a5
Revises: 98db2d1fd64f
Create Date: 2025-03-29 22:58:40.520834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87a2e836d4a5'
down_revision: Union[str, None] = '98db2d1fd64f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_user_title', 'categories', ['user_id', 'title'])
    op.alter_column('notes', 'text',
               existing_type=sa.TEXT(),
               type_=sa.String(length=5000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'text',
               existing_type=sa.String(length=5000),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uix_user_title', 'categories', type_='unique')
    # ### end Alembic commands ###
