name: Deploy to Server

on:
  push:
    branches:
      - main  # Запускать workflow при пуше в ветку main

jobs:
  build_and_push_to_docker_hub:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./src/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/simple_notes_bot:latest

  deploy:
    runs-on: ubuntu-latest
    needs: 
        - build_and_push_to_docker_hub
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Клонирует репозиторий в рабочую директорию

      # - name: Copy nginx.conf
      #   uses: appleboy/scp-action@v0.1.0
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USER }}
      #     password: ${{ secrets.PASSWORD }}  # Используйте password или key
      #     # key: ${{ secrets.SSH_KEY }}     # Если используете SSH-ключ
      #     source: "infra/nginx.conf"  # Путь к файлу относительно корня репозитория
      #     target: "/home/simple_notes_bot/"  # Путь на удаленном сервере

      - name: Copy docker-compose.yml
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}  # Используйте password или key
          # key: ${{ secrets.SSH_KEY }}     # Если используете SSH-ключ
          source: "infra/docker-compose.yml"  # Путь к файлу относительно корня репозитория
          target: "/home/simple_notes_bot/"  # Путь на удаленном сервере


      - name: Executing remote commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/simple_notes_bot/infra/
            docker compose -f docker-compose.yml pull
            docker compose -f docker-compose.yml down
            docker compose -f docker-compose.yml up -d
            docker system prune -a -f
