name: Deploy to Server

on:
  push:
    branches:
      - main  # Запускать workflow при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Клонирует репозиторий в рабочую директорию

      - name: Copy file via SCP
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}  # Используйте password или key
          # key: ${{ secrets.SSH_KEY }}     # Если используете SSH-ключ
          source: "888.txt"  # Путь к файлу относительно корня репозитория
          target: "/root/simple_notes_bot/"  # Путь на удаленном сервере