name: simple_notes_bot workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test_copy:
    runs-on: ubuntu-latest
    steps:
      - name: List files in infra/
        run: |
          ls -R infra/