name: Print Current Directory

on:
  push:
    branches:
      - main

jobs:
  print-directory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print current directory
        run: |
          echo "Текущая папка: $(pwd)"