name: Debug Workflow

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print current directory
        run: |
          echo "Текущая папка: $(pwd)"

      - name: List files after checkout
        run: |
          ls -R